### ISSUE TITLE
Polymer 3.0 version

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-starter-kit#1080]

**Comment by mercmobily** [comment]
I am starting a new project next week, and was wondering if you guys are releasing a Polymer 3 version of this soon enough.
I think P3 is nearly ready... so this would be GOLD.

Let us know :D

**Comment by moderndeveloperllc** [comment]
@mercmobily They wont get to this until 3.0 has been released at least as RC. There are still some [Google-authored elements](https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md) that need to work with Modulizer. Even with that, there will be issues for awhile with 3rd-party components that will need a bit of work to function correctly.

If you are starting next week, I would suggest making a good, tested, 2.5 application using the new `static get template() {}` structure with ES6 classes. When 3 gets *really* stable (around 3.1 probably), you should be able to run Modulizer to convert over your app and dependancies over to the new JS-only architecture.

**Comment by silentHoo** [comment]
@mercmobily May this is what you want: https://github.com/Polymer/polymer-starter-kit/releases/tag/v3.2.1 :)

**Comment by mercmobily** [comment]
Hi,

Wow, this came out yesterday!

If I want zero tech debt for the new project, do you think this is the way
to go?

Merc.

**Comment by silentHoo** [comment]
@mercmobily Sorry my fault, the version resolves to `"polymer": "^2.0.0"`. See the `bower.json` the project uses.

If I would start a new project with Polymer I would begin with the current Preview. In the blog are some details to get started:https://www.polymer-project.org/blog/2018-01-18-polymer-3-new-preview.

Hope this will help you.

**Comment by moderndeveloperllc** [comment]
@mercmobily PSK 3.2.1 is a Polymer 2.0 skeleton. Actually, they haven't yet changed over to the `static get template() {}` structure (Polymer 2.4+), but that's an easy enough thing for you to do with your own elements. There is no branch I can see here or with any of the main contributors where they have reworked the PSK to be Polymer 3 with the whole JS modules/yarn/npm structure. There are *many* projects (-build, -bundler, -cli, -analyzer, WCT, more I can't remember) that will have to be updated to work with Polymer 3 seamlessly before a PSK 4 is viable. @justinfagnani is a major contributor on those FWIW. I'll stand by by original recommendation.

I deeply empathize with the desire to have no tech debt at the beginning, and if you have the time to deal with alpha software, download PSK 3.2.1, update your project's `bower.json` to point to the Poymer 3 preview branch, install and run [`polymer-modulizer`](https://github.com/Polymer/polymer-modulizer) and have at it. 

But unless this project is supposed to be 6-9 months of dev time before deploy and you are comfortable with mass changes throughout that time, I would stick with Polymer 2.5. There are supposed to be no major API changes from that to 3.0, and when all your 3rd-party dependancies have been updated to the JS module/yarn/npm ecosystem, you should be able to run `polymer-modulizer` to update to Polymer 3.

**Comment by justinfagnani** [comment]
Assigning to @aomarks to try and verify

**Comment by bicknellr** [comment]
(closing due to the preview being available)
