### ISSUE TITLE
Sub par performance on lighthouse in Chrome v62 for `es6-unbundled` build

### ISSUE THREAD

**Issue by andrewspy** [Polymer/polymer-starter-kit#1082]
### Description
Sub par performance on lighthouse in Chrome v62 out of the box in localhost setup, using `polymer init` and `polymer serve`.

### Expected outcome

lighthouse performance should be in the 90+/100. With first pain/interactive within few sec, with a Perceptual Speed Index of less than 1,250.

### Actual outcome

lighthouse performance index of only 30/100. With first paint/interactive at 13+/13+ sec respectively, with a Perceptual Speed Index of 14,000.

### Live Demo

N/A

### Steps to reproduce

1. `polymer init` with `polymer-starter-kit` v3.2
2. `polymer serve`
3. Audit with lighthouse in Chrome v62

### Browsers Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by abdonrd** [comment]
Did you build the project for production?
You should have this score: https://github.com/PolymerElements/polymer-starter-kit/pull/1075

**Comment by andrewspy** [comment]
@abdonrd Thanks for the reference on #1071, which I have missed the step of building for production.

I guess the major problem I am having with my build is I'm using `es6-unbundled` build, which has "Critical Request Chain" of 87 (instead of 2 for `es6-bundled`).

Given that I am hosting my PWA in Firebase Hosting (which support HTTP/2), should I target my build to `es6-bundled`? I though `es6-unbundled` can take advantages of Server Push support in HTTP/2? Does it mean there is a trade-off for having faster first paint vs granular Server Push?

**Comment by abdonrd** [comment]
The `polymer-build` has an issue to improve the `push-manifest.json`: https://github.com/Polymer/polymer-build/issues/260

Meanwhile, in the `Polymer/shop` I see some scripts: https://github.com/Polymer/shop/pull/145

**Comment by andrewspy** [comment]
@abdonrd Do you know if there is there any plan to resolve the shortfall of having `es6-unbundled` build? At this stage, `es6-unbundled` build simply doesn't pass the audit of lighthouse out of the box...

**Comment by abdonrd** [comment]
I have no idea. 😕 
The last message I read was: https://github.com/Polymer/polymer-build/issues/260#issuecomment-342240313
