### ISSUE TITLE
<app-header-layout has-scrolling-region> has additional unwanted "scroll region" on mobile chrome

### ISSUE THREAD

**Issue by andrewspy** [Polymer/polymer-starter-kit#1089]
### Description

When using on mobile Chrome with a page that is larger than the mobile screen, an additional unwanted "scroll region" appears when scroll all the way to the end of the screen (where the Chrome Address Bar fades away), and scroll back up.

This is a known limitation as reference in https://github.com/PolymerElements/app-layout/issues/533, which I think should not be there "out-of-the-box" for the new user. Not sure if PSK want to change it's `<app-header-layout has-scrolling-region>` to `<app-header-layout fullbleed>` in order to remove the known limitation.

### Expected outcome

No additional unwanted "scroll region".

### Actual outcome

![36064290-c2bc7d7e-0ec3-11e8-8a8f-29490af9fa3c](https://user-images.githubusercontent.com/3106425/36355654-813755fe-1521-11e8-97d4-6b8903e0ff87.png)

Additional unwanted "scroll region" visible at the bottom.

### Live Demo

See: https://github.com/PolymerElements/app-layout/issues/533

### Steps to reproduce

See: https://github.com/PolymerElements/app-layout/issues/533

### Browsers Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by halloweenman** [comment]
I was having some scroll issues with mobile safari.

    app-drawer-layout {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
    }

Fixed the issues for me.
