### ISSUE TITLE
Polymer 3, Edge 17

### ISSUE THREAD

**Issue by jrmerz** [Polymer/polymer-starter-kit#1108]
### Description

Following the polymer 3 preview branch instructions Edge 17 shows a blank page.   Logs no errors to console.

### Expected outcome

You should be able to see see the starter kit app in Edge 17.

### Actual outcome

Blank page

### Steps to reproduce

```
npm install -g polymer-cli@next
```

```
mkdir my-app
cd my-app
polymer init polymer-3-starter-kit
```

### Browsers Affected

- [ ] Chrome
- [x] Edge 17
- [ ] Firefox
- [ ] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by bicknellr** [comment]
How are you serving the app? `polymer serve`?

**Comment by jrmerz** [comment]
Working now.  Was trying with a pre stable 2.0.0 webcomponentsjs, my guess is that was the issue.
